apiVersion: v1
kind: Secret
metadata:
  name: imagomortis-db-secret
  namespace: imagomortis
  labels:
    app.kubernetes.io/name: imagomortis
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: imagomortis
type: Opaque
stringData:
  # Change these values in production!
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
