{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imagomortis.secretName" . }}
  namespace: {{ include "imagomortis.namespace" . }}
  labels:
    {{- include "imagomortis.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  {{ .Values.database.secretKeys.username }}: {{ .Values.postgresql.auth.username | quote }}
  {{ .Values.database.secretKeys.password }}: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
